FROM spark:3.5.1-scala2.12-java17-ubuntu

USER root

RUN set -ex; \
    apt-get update; \
    apt-get install -y python3 python3-pip; \
    rm -rf /var/lib/apt/lists/*

#Copy requirements file to docker container
COPY requirements.txt .

#Install all requirements
RUN pip install --no-cache-dir -r requirements.txt

# Clear Ivy cache
RUN rm -rf /root/.ivy2/cache && rm -rf /root/.ivy2/jars

USER spark

#Get pipeline code-location
COPY ./finnhub-batch-stock-pipeline/ /

WORKDIR /
