version: '3.7'
 
services:
 registry:
   restart: always
   image: registry:2
   ports:
   - "5000:5000"
   environment:
     REGISTRY_AUTH: htpasswd
     REGISTRY_AUTH_HTPASSWD_REALM: Registry
     REGISTRY_AUTH_HTPASSWD_PATH: /a2auth/registry.password
     REGISTRY_HTTP_SECRET: xtn2Qt6iqdn1ih5IAteEa6dz5hAXN6r3
     REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /main
     REGISTRY_STORAGE_DELETE_ENABLED: ‘true’
   volumes:
     - ./main:/main
     - ./a2auth:/a2auth
