dagster-user-deployments:
  enabled: true
  deployments:
    - name: "k8s-deployment"
      image:
        repository: "docker.io/library/fnhb-btch-stck-ppln"
        tag: v1.0.0
        pullPolicy: Never
      dagsterApiGrpcArgs:
        - "--module-name"
        - "finnhub_batch_stock_pipeline"
      port: 3030
      envConfigMaps:
        - name: pipeline-config
      envSecrets:
        - name: pipeline-secrets
      resources:
        limits:
          cpu: 1000m
          memory: 4096Mi
        requests:
          cpu: 500m
          memory: 2048Mi
      includeConfigInLaunchedRuns:
        enabled: false

runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      imagePullPolicy: IfNotPresent
      volumes:
        - name: nfs-mount
          persistentVolumeClaim:
            claimName: nfs-pvc
      volumeMounts:
        - name: nfs-mount
          mountPath: /opt/dagster/dagster_home
      runK8sConfig:
        containerConfig: # raw config for the pod's main container
          image: docker.io/library/fnhb-btch-stck-ppln:v1.1.0
          resources:
            limits:
              cpu: 8000m
              memory: 32768Mi
            requests:
              cpu: 4000m
              memory: 20480Mi
      envConfigMaps:
        - name: pipeline-config
      envSecrets:
        - name: pipeline-secrets


