dagster-user-deployments:
  enabled: true
  deployments:
    - name: "k8s-deployment"
      image:
        repository: "docker.io/library/fnhb-btch-stck-ppln"
        tag: v1.0.0
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--module-name"
        - "finnhub_batch_stock_pipeline/"
      port: 3030
      envSecrets:
        - name: dagster-aws-access-key-id
        - name: dagster-aws-secret-access-key

runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      envSecrets:
        - name: dagster-aws-access-key-id
        - name: dagster-aws-secret-access-key