# dagster-user-deployments:
#   enabled: true
#   deployments:
#     - name: "k8s-deployment"
#       image:
#         repository: "docker.io/library/fnhb-btch-stck-ppln"
#         tag: latest
#         pullPolicy: IfNotPresent
#       dagsterApiGrpcArgs:
#         - "--module-name"
#         - "finnhub_batch_stock_pipeline/"
#       port: 3030
#       envConfigMaps:
#         - name: pipeline-config
#       envSecrets:
#         - name: pipeline-secrets
#       includeConfigInLaunchedRuns:
#         enabled: true

# runLauncher:
#   type: K8sRunLauncher
#   config:
#     k8sRunLauncher:
#       envSecrets:
#         - name: pipeline-secrets


# # labels:
# #         foo_label: bar_value
# #       volumes:
# #         - name: my-volume
# #           configMap: my-config-map
# #       volumeMounts:
# #         - name: test-volume
# #           mountPath: /opt/dagster/test_folder
# #           subPath: test_file.yaml
# #       resources:
# #         limits:
# #           cpu: 100m
# #           memory: 128Mi
# #         requests:
# #           cpu: 100m
# #           memory: 128Mi
      